//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReMarsModTool.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReMarsModTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add Astroid (not implemented) 的本地化字符串。
        /// </summary>
        public static string AddAstroid {
            get {
                return ResourceManager.GetString("AddAstroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Building 的本地化字符串。
        /// </summary>
        public static string AddBuilding {
            get {
                return ResourceManager.GetString("AddBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Item 的本地化字符串。
        /// </summary>
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Research 的本地化字符串。
        /// </summary>
        public static string AddResearch {
            get {
                return ResourceManager.GetString("AddResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Unit 的本地化字符串。
        /// </summary>
        public static string AddUnit {
            get {
                return ResourceManager.GetString("AddUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Unity Assets 的本地化字符串。
        /// </summary>
        public static string AddUnityAssetsButton {
            get {
                return ResourceManager.GetString("AddUnityAssetsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Clone Buildings to Mod 的本地化字符串。
        /// </summary>
        public static string BatchCloneBuildingsToMod {
            get {
                return ResourceManager.GetString("BatchCloneBuildingsToMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Clone Units 的本地化字符串。
        /// </summary>
        public static string BatchCloneUnits {
            get {
                return ResourceManager.GetString("BatchCloneUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Modify Buildings 的本地化字符串。
        /// </summary>
        public static string BatchModifyBuildings {
            get {
                return ResourceManager.GetString("BatchModifyBuildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Modify Units 的本地化字符串。
        /// </summary>
        public static string BatchModifyUnits {
            get {
                return ResourceManager.GetString("BatchModifyUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The batch operation will overwrite all existing items. Continue? 的本地化字符串。
        /// </summary>
        public static string BatchOpWarning {
            get {
                return ResourceManager.GetString("BatchOpWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Process 的本地化字符串。
        /// </summary>
        public static string BatchProcess {
            get {
                return ResourceManager.GetString("BatchProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Bg1 {
            get {
                object obj = ResourceManager.GetObject("Bg1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Browse... 的本地化字符串。
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clone current building 的本地化字符串。
        /// </summary>
        public static string CloneBuilding {
            get {
                return ResourceManager.GetString("CloneBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string ErrorMsgBoxTitle {
            get {
                return ResourceManager.GetString("ErrorMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error opening registry key! Cannot determine where is the ReMars installed.  的本地化字符串。
        /// </summary>
        public static string ErrorTextOpeningRegKey {
            get {
                return ResourceManager.GetString("ErrorTextOpeningRegKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string LanguageColumnHeader {
            get {
                return ResourceManager.GetString("LanguageColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string LoadingSuffixText {
            get {
                return ResourceManager.GetString("LoadingSuffixText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading... 的本地化字符串。
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Configurations 的本地化字符串。
        /// </summary>
        public static string ModConfigurations {
            get {
                return ResourceManager.GetString("ModConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modding 的本地化字符串。
        /// </summary>
        public static string Modding {
            get {
                return ResourceManager.GetString("Modding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Editor 的本地化字符串。
        /// </summary>
        public static string ModEditorWindowTitle {
            get {
                return ResourceManager.GetString("ModEditorWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Folder: 的本地化字符串。
        /// </summary>
        public static string ModFolderLabel {
            get {
                return ResourceManager.GetString("ModFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Name: 的本地化字符串。
        /// </summary>
        public static string ModNameLabel {
            get {
                return ResourceManager.GetString("ModNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reshaping Mars Modding Tool (Unofficial) 的本地化字符串。
        /// </summary>
        public static string ModToolTitle {
            get {
                return ResourceManager.GetString("ModToolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modding Tool (Unofficial) 的本地化字符串。
        /// </summary>
        public static string ModToolUnofficial {
            get {
                return ResourceManager.GetString("ModToolUnofficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to manually specify where the game is installed? 的本地化字符串。
        /// </summary>
        public static string NotifyManualSelectInstallDir {
            get {
                return ResourceManager.GetString("NotifyManualSelectInstallDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview Picture: 的本地化字符串。
        /// </summary>
        public static string PreviewPictureLabel {
            get {
                return ResourceManager.GetString("PreviewPictureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Question 的本地化字符串。
        /// </summary>
        public static string QuestionMsgBoxTitle {
            get {
                return ResourceManager.GetString("QuestionMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reshaping Mars 的本地化字符串。
        /// </summary>
        public static string ReMarsTitle {
            get {
                return ResourceManager.GetString("ReMarsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As 的本地化字符串。
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the ReshapingMars.exe file 的本地化字符串。
        /// </summary>
        public static string SelectReMarsExe {
            get {
                return ResourceManager.GetString("SelectReMarsExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buildings 的本地化字符串。
        /// </summary>
        public static string StepInitBuildings {
            get {
                return ResourceManager.GetString("StepInitBuildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Items 的本地化字符串。
        /// </summary>
        public static string StepInitItems {
            get {
                return ResourceManager.GetString("StepInitItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Land Resources 的本地化字符串。
        /// </summary>
        public static string StepInitLandRes {
            get {
                return ResourceManager.GetString("StepInitLandRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layers 的本地化字符串。
        /// </summary>
        public static string StepInitLayers {
            get {
                return ResourceManager.GetString("StepInitLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game meta file 的本地化字符串。
        /// </summary>
        public static string StepInitReMarsMainMeta {
            get {
                return ResourceManager.GetString("StepInitReMarsMainMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game path 的本地化字符串。
        /// </summary>
        public static string StepInitReMarsPath {
            get {
                return ResourceManager.GetString("StepInitReMarsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Researches 的本地化字符串。
        /// </summary>
        public static string StepInitResearch {
            get {
                return ResourceManager.GetString("StepInitResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Units 的本地化字符串。
        /// </summary>
        public static string StepInitUnits {
            get {
                return ResourceManager.GetString("StepInitUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation 的本地化字符串。
        /// </summary>
        public static string TranslationColumnHeader {
            get {
                return ResourceManager.GetString("TranslationColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Name Translations: 的本地化字符串。
        /// </summary>
        public static string TranslationsLabel {
            get {
                return ResourceManager.GetString("TranslationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
